/**
 * @sharghigold/contracts — the API contract, shared by server and client.
 *
 * These schemas are the single definition of what the system accepts and
 * returns. The API parses requests with them; the storefront validates forms
 * and types responses with them. Because both sides import the same object,
 * the contract cannot silently drift.
 *
 * Client-side use is a convenience for fast feedback, never a control: the
 * server re-parses everything it receives.
 */

export {
  ageInYears,
  basisPointsSchema,
  iranianIbanSchema,
  iranianMobileSchema,
  iranianNationalIdSchema,
  isValidIranianIban,
  isValidIranianNationalId,
  isValidJalaliDate,
  jalaliDateSchema,
  jalaliToGregorian,
  karatSchema,
  maskIranianMobile,
  milligramsStringSchema,
  otpCodeSchema,
  positiveRialsStringSchema,
  rialsStringSchema,
  slugSchema,
  stripControlCharacters,
  userTextSchema,
  uuidSchema,
  type IranianMobile,
  type Karat,
} from './primitives.js';

export {
  ADMIN_PERMISSIONS,
  actorTypeSchema,
  adminOrderSummarySchema,
  adminPermissionSchema,
  adminRoleSchema,
  adminUserSchema,
  auditEntrySchema,
  can,
  dashboardSchema,
  DEFAULT_ADMIN_ROLES,
  metricSchema,
  permissionsOf,
  productDraftSchema,
  productStatusSchema,
  refundRequestSchema,
  stockAdjustmentSchema,
  type AdminOrderSummary,
  type AdminPermission,
  type AdminRole,
  type AdminUser,
  type AuditEntry,
  type Dashboard,
  type DefaultAdminRole,
  type Metric,
  type ProductDraft,
  type RefundRequest,
  type StockAdjustment,
} from './admin.js';

export {
  API_ERROR_CODES,
  API_ERROR_STATUS,
  apiErrorCodeSchema,
  apiErrorSchema,
  apiFailureSchema,
  apiResponseSchema,
  apiSuccessSchema,
  fieldErrorSchema,
  type ApiError,
  type ApiErrorCode,
  type ApiFailure,
  type ApiResponse,
  type ApiSuccess,
  type FieldError,
} from './api.js';

export {
  buildPageMeta,
  cursorPagedSchema,
  cursorQuerySchema,
  DEFAULT_PAGE_SIZE,
  MAX_PAGE_SIZE,
  pageMetaSchema,
  pageQuerySchema,
  pagedSchema,
  sortDirectionSchema,
  sortQuerySchema,
  type CursorQuery,
  type PageMeta,
  type PageQuery,
  type SortDirection,
} from './pagination.js';

export {
  categoryNavigationEntrySchema,
  categoryNavigationSchema,
  categorySummarySchema,
  facetGroupKindSchema,
  facetGroupSchema,
  facetQuerySchema,
  facetTileSchema,
  iconKeySchema,
  type CategoryNavigation,
  type CategoryNavigationEntry,
  type CategorySummary,
  type FacetGroup,
  type FacetGroupKind,
  type FacetTile,
  type IconKey,
} from './catalogue.js';

export {
  DEFAULT_LISTING_QUERY,
  DEFAULT_PRODUCT_SORT,
  LISTING_MAX_PAGE,
  LISTING_PAGE_SIZE,
  listingQuerySchema,
  parseListingQuery,
  productSummarySchema,
  productListingSchema,
  productSortSchema,
  searchTermSchema,
  type ListingQuery,
  type ProductSummary,
  type ProductListing,
  type ProductSort,
} from './listing.js';

export {
  DEFAULT_MAGAZINE_SORT,
  MAGAZINE_MAX_PAGE,
  MAGAZINE_PAGE_SIZE,
  magazineArchiveQuerySchema,
  magazineSearchTermSchema,
  magazineSlugSchema,
  magazineSortSchema,
  parseMagazineArchiveQuery,
  parseMagazineSearch,
  type MagazineArchiveQuery,
  type MagazineSort,
} from './magazine.js';

export {
  breadcrumbStepSchema,
  goldColourSchema,
  productColourSchema,
  productDetailSchema,
  productMediaSchema,
  productSizeSchema,
  productSpecSchema,
  ratingBucketSchema,
  ratingSummarySchema,
  sizeGuideRowSchema,
  skuSchema,
  starRatingSchema,
  type BreadcrumbStep,
  type GoldColour,
  type ProductColour,
  type ProductDetail,
  type ProductMedia,
  type ProductSize,
  type ProductSpec,
  type RatingSummary,
  type SizeGuideRow,
} from './product.js';

export {
  goldRateSnapshotSchema,
  INSTALLMENT_QUOTE_MAX_TOMAN,
  INSTALLMENT_QUOTE_MIN_TOMAN,
  installmentAmountTomanSchema,
  installmentPlanSchema,
  priceLineKindSchema,
  priceLineSchema,
  priceQuoteSchema,
  type GoldRateSnapshot,
  type InstallmentPlan,
  type PriceLine,
  type PriceLineKind,
  type PriceQuote,
} from './pricing.js';

export {
  aspectRatingSchema,
  aspectScoreSchema,
  contributionIdSchema,
  productQuestionSchema,
  productReviewSchema,
  QUESTION_BODY_MAX,
  QUESTION_BODY_MIN,
  questionAnswerSchema,
  questionSubmissionSchema,
  REVIEW_BODY_MAX,
  REVIEW_BODY_MIN,
  reviewAspectSchema,
  reviewFilterSchema,
  reviewPageSchema,
  reviewPhotoSchema,
  reviewQuerySchema,
  reviewSortSchema,
  reviewSubmissionSchema,
  sellerReplySchema,
  type AspectScore,
  type ProductQuestion,
  type ProductReview,
  type QuestionSubmission,
  type ReviewAspect,
  type ReviewFilter,
  type ReviewPage,
  type ReviewQuery,
  type ReviewSort,
  type ReviewSubmission,
} from './reviews.js';

export {
  currentSessionSchema,
  requestOtpResultSchema,
  requestOtpSchema,
  sessionUserSchema,
  verifyOtpResultSchema,
  verifyOtpSchema,
  type CurrentSession,
  type RequestOtpInput,
  type RequestOtpResult,
  type SessionUser,
  type VerifyOtpInput,
  type VerifyOtpResult,
} from './auth.js';

export {
  accountOverviewSchema,
  accountProfileSchema,
  activeOrderSchema,
  addressDraftSchema,
  addressLabelSchema,
  addressSchema,
  deviceKindSchema,
  deviceSessionSchema,
  kycBankSchema,
  kycIdentitySchema,
  kycProgressSchema,
  kycSelfieSchema,
  kycStatusSchema,
  kycStepKeySchema,
  kycStepStateSchema,
  orderStateSchema,
  PASSWORD_MAX,
  PASSWORD_MIN,
  passwordLoginSchema,
  passwordSchema,
  postalCodeSchema,
  profileUpdateSchema,
  setPasswordSchema,
  walletSummarySchema,
  type AccountOverview,
  type AccountProfile,
  type ActiveOrder,
  type Address,
  type AddressDraft,
  type AddressLabel,
  type DeviceKind,
  type DeviceSession,
  type KycBankInput,
  type KycIdentityInput,
  type KycProgress,
  type KycSelfieInput,
  type KycStatus,
  type KycStepKey,
  type KycStepState,
  type OrderState,
  type PasswordLoginInput,
  type ProfileUpdateInput,
  type SetPasswordInput,
  type WalletSummary,
} from './account.js';

export {
  isGsmText,
  isOptionalPurpose,
  isRetryableStatus,
  isSettledStatus,
  OPTIONAL_SMS_PURPOSES,
  SMS_DELIVERY_STATUSES,
  SMS_PURPOSES,
  SMS_SEGMENT_GSM,
  SMS_SEGMENT_GSM_MULTIPART,
  SMS_SEGMENT_UNICODE,
  SMS_SEGMENT_UNICODE_MULTIPART,
  SMS_SEND_FAILURES,
  SMS_TEXT_MAX,
  smsAccountInfoSchema,
  smsDeliveryStatusSchema,
  smsDispatchSchema,
  smsMessageIdSchema,
  smsPurposeSchema,
  smsSegments,
  smsSendFailureSchema,
  smsSendRequestSchema,
  smsSendResultSchema,
  smsStatusQuerySchema,
  smsStatusReportSchema,
  smsTraceIdSchema,
  type SmsAccountInfo,
  type SmsDeliveryStatus,
  type SmsDispatch,
  type SmsPurpose,
  type SmsSendFailure,
  type SmsSendRequest,
  type SmsSendResult,
  type SmsStatusQuery,
  type SmsStatusReport,
} from './sms.js';

export {
  paymentMethodSchema,
  paymentStatusSchema,
  TOP_UP_MAX_RIALS,
  TOP_UP_MIN_RIALS,
  TOP_UP_QUICK_RIALS,
  topUpReceiptSchema,
  topUpTomanSchema,
  walletStateSchema,
  type PaymentMethod,
  type PaymentStatus,
  type TopUpReceipt,
  type WalletState,
} from './wallet.js';

export {
  addToCartSchema,
  appliedDiscountSchema,
  billLineKindSchema,
  billLineSchema,
  CART_MAX_LINES,
  CART_MAX_QUANTITY,
  cartLineSchema,
  cartQuantitySchema,
  cartTotalsSchema,
  cartViewSchema,
  checkoutPaymentSchema,
  companyDetailsSchema,
  deliveryModeSchema,
  discountCodeSchema,
  discountKindSchema,
  installmentOfferSchema,
  invoiceTypeSchema,
  ORDER_NOTE_MAX,
  orderCodeSchema,
  orderNoteSchema,
  orderPaymentStateSchema,
  otherRecipientSchema,
  placedOrderSchema,
  savedLineSchema,
  shippingMethodSchema,
  type AddToCartInput,
  type AppliedDiscount,
  type BillLine,
  type BillLineKind,
  type CartLine,
  type CartTotals,
  type CartView,
  type CheckoutPayment,
  type CompanyDetails,
  type DeliveryMode,
  type DiscountKind,
  type InstallmentOffer,
  type InvoiceType,
  type OrderPaymentState,
  type OtherRecipient,
  type PlacedOrder,
  type SavedLine,
  type ShippingMethod,
} from './cart.js';

export {
  cancelOrderSchema,
  cancelReasonSchema,
  instalmentPlanSchema,
  instalmentSchema,
  ORDER_MESSAGE_MAX,
  ORDER_NOTE_LIMIT,
  ORDER_SEARCH_MAX,
  orderAllowancesSchema,
  orderBillSchema,
  orderEventKindSchema,
  orderEventSchema,
  orderFileSchema,
  orderGroupSchema,
  orderLineSchema,
  orderListQuerySchema,
  orderMessageInputSchema,
  orderMessageSchema,
  orderOutcomeSchema,
  orderReturnSchema,
  parseOrderListQuery,
  refundDestinationSchema,
  returnOrderSchema,
  returnReasonSchema,
  returnStageSchema,
  reviewOrderSchema,
  reviewTagSchema,
  type CancelOrderInput,
  type CancelReason,
  type Instalment,
  type OrderAllowances,
  type OrderBill,
  type OrderEvent,
  type OrderEventKind,
  type OrderFile,
  type OrderGroup,
  type OrderInstalmentPlan,
  type OrderLine,
  type OrderListQuery,
  type OrderMessage,
  type OrderMessageInput,
  type OrderOutcome,
  type OrderReturn,
  type RefundDestination,
  type ReturnOrderInput,
  type ReturnReason,
  type ReturnStage,
  type ReviewOrderInput,
  type ReviewTag,
} from './orders.js';
